server:
  port: 8081

spring:
  application:
    name: SECURITY-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/strivelabs
    username: postgres
    password: $anjay1@2
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

